#pragma config(Motor,  port2,           leftFrontMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftBackMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           rightBackMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           rightFrontMotor, tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true){
	motor[leftFrontMotor] = vexRT[Ch3];
	motor[leftBackMotor] = vexRT[Ch3];
	motor[rightFrontMotor] = vexRT[Ch3];
	motor[rightBackMotor] = vexRT[Ch3];
	
  motor[leftFrontMotor] = vexRT[Ch4];
	motor[leftBackMotor] = vexRT[Ch4];
	motor[rightFrontMotor] = -1*vexRT[Ch4];
	motor[rightBackMotor] = -1*vexRT[Ch4];
	
	}//main loop


}
